from fastapi import APIRouter , HTTPException 
from api.schemas import (ChatRequest,
                         ChatResponse,
                         EscalationApprovalResponse,
                         EscalationAprrovalRequest)

from services.agent_graph import app
from langgraph.types import Command
from langchain_core.messages import HumanMessage
import traceback



router=APIRouter()

@router.post("/chat", response_model=ChatResponse)
async def chat_endpoint(payload: ChatRequest):
    """
    Main endpoint for user chat messages.
    Receives user message -> Runs LangGraph -> Returns AI text OR Interrupted status.
    """
    # 1. Config tells LangGraph WHICH session memory thread to load/save
    config = {"configurable": {"thread_id": payload.thread_id}}

    # 2. Wrap incoming raw string into a LangChain HumanMessage
    inputs = {"messages": [HumanMessage(content=payload.message)]}

    try:
        # 3. Stream graph execution node-by-node.
        # This loop continues until:
        #   a) Graph finishes completely (hits END)
        #   b) Graph hits interrupt() in escalation_node and pauses automatically
        for _ in app.stream(inputs, config=config, stream_mode="values"):
            pass

        # 4. Inspect the resulting state of the graph for this thread
        current_state = app.get_state(config)

        # 5. CHECK: Did the graph pause due to an interrupt() call?
        if current_state.tasks and current_state.tasks[0].interrupts:
            # Extract payload passed inside interrupt({...})
            interrupt_data = current_state.tasks[0].interrupts[0].value
            
            return ChatResponse(
                thread_id=payload.thread_id,
                status="INTERRUPTED",
                response=(
                    "Your request involves custom Enterprise requirements (such as On-Premise deployment). "
                    "Our Senior Sales Director has been notified to review and approve your request."
                ),
                interrupt_details=interrupt_data
            )

        # 6. IF NOT INTERRUPTED: Retrieve the last AIMessage generated by the agent
        messages = current_state.values.get("messages", [])
        if not messages:
            raise HTTPException(status_code=500, detail="Graph state returned no messages.")

        last_message = messages[-1]

        return ChatResponse(
            thread_id=payload.thread_id,
            status="COMPLETED",
            response=last_message.content
        )

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error processing chat: {str(e)}")

@router.get("/pending_reviews/{thread_id}")
async def check_pending_reviews(thread_id:str):
    config={"configurable":{"thread_id:thread_id}"}}
    current_state=app.get_state(config)
    if current_state.tasks and current_state.tasks[0].interrupts:
        return {"thread_id":thread_id,
                "status":"Waiting for Approval",
                "interrupt_details":current_state.tasks[0].interrupts[0].value}
    return{"thread_id":thread_id,
           "status":"No need for Approval"}

@router.post("/approve_escalation",response_model=EscalationApprovalResponse)
async def approve_escalation_endpoint(payload:EscalationAprrovalRequest):
    config={"configurable":{"thread_id":payload.thread_id}}
    current_state=app.get_state(config)
    if not(current_state.tasks and current_state.tasks[0].interrupts):
        raise HTTPException(status_code=400,
                            detail=f"Thread '{payload.thread_id}' is not currently paused on an interrupt.")
    try:
        resume_command = Command(resume={"response": payload.decision})

        for _ in app.stream(resume_command, config=config, stream_mode="values"):
            pass
            final_state = app.get_state(config)
            final_messages = final_state.values.get("messages", [])
            last_msg = final_messages[-1] if final_messages else None
        
            return EscalationApprovalResponse(
                    thread_id=payload.thread_id,
                    status="RESUMED_AND_COMPLETED",
                    final_response=last_msg.content if last_msg else "Execution resumed successfully."
                )
        
    except Exception as e:
                raise HTTPException(status_code=500, detail=f"Error resuming graph: {str(e)}")    