import { Link } from 'react-router-dom'
import { ArrowRight, Check, GitBranch, ShieldCheck } from 'lucide-react'
import { Button } from '../components/ui/Button'
import { Container } from '../components/ui/Container'
import { Card } from '../components/ui/Card'
import { Section } from '../components/ui/Section'
import { integrations } from '../data/integrations'

export function PlaceholderPage({ kind = 'platform' }: { kind?: 'platform' | 'security' | 'how' }) {
  const platform = kind === 'platform'
  const security = kind === 'security'
  const title = platform ? 'Confidence in every change.' : security ? 'Built for your trust boundary.' : 'From pull request to signal.'
  const intro = platform ? 'Explore code review, refactoring, scanning, and architecture guardrails built for pull request workflows.' : security ? 'Keep review and deployment aligned with the trust boundary your organization requires.' : 'Connect your Git provider, open a pull request, and get focused findings and fixes where your team already works.'
  const sections = platform ? ['Real-time pull request code reviews', 'Automated refactoring suggestions', 'Dependency and secret scanning', 'Architecture and performance guardrails'] : security ? ['Deployment options', 'Compliance', 'Data handling', 'Product security features'] : ['Connect your Git provider', 'Open a pull request', 'Get a review with findings and fixes', 'Route alerts to your team', 'Scale to Enterprise deployment']
  return <>
    <section className={`texture ${security ? 'bg-crimson text-cream' : ''} py-20 md:py-28`}><Container><p className={`font-mono text-xs uppercase tracking-[.2em] ${security ? 'text-mist' : 'text-crimson'}`}>{platform ? 'Platform' : security ? 'Security' : 'How it works'}</p><h1 className="mt-5 max-w-3xl font-display text-5xl tracking-tight sm:text-6xl">{title}</h1><p className={`mt-6 max-w-2xl text-lg leading-8 ${security ? 'text-cream/80' : 'text-ink-soft'}`}>{intro}</p><Link to="/chat" className="mt-8 inline-block"><Button className={security ? 'bg-cream text-crimson hover:bg-sand' : ''}>{security ? 'Request an enterprise discovery call' : 'Talk to an AI Sales Engineer'} <ArrowRight size={17} /></Button></Link></Container></section>
    <Section><Container><div className="space-y-5">{sections.map((item, i) => <Card key={item} className="grid gap-5 p-7 md:grid-cols-[80px_1fr] md:items-center"><div className="flex h-14 w-14 items-center justify-center rounded-full bg-mist text-crimson">{security ? <ShieldCheck /> : platform ? <Check /> : <GitBranch />}</div><div><p className="font-mono text-xs uppercase tracking-[.16em] text-crimson">0{i + 1}</p><h2 className="mt-2 font-display text-2xl">{item}</h2><p className="mt-2 max-w-2xl leading-7 text-ink-soft">{security && i === 0 ? 'Enterprise deployment can be multi-tenant cloud, single-tenant VPC, or air-gapped on-premises.' : security && i === 1 ? 'Enterprise compliance reports include SOC2 Type II, ISO 27001, and HIPAA.' : security && i === 2 ? 'Enterprise includes a zero-data-retention policy.'     : platform ? ['Find security issues, logic flaws, memory leaks, and performance bottlenecks in the pull request.', 'Turn findings into clear, actionable refactoring suggestions.', 'Catch exposed API keys, private tokens, and vulnerable dependencies before they ship.', 'Surface high-complexity functions, N+1 query patterns, and architectural regressions.'][i] : ['Connect GitHub, GitLab Cloud, or Bitbucket Cloud according to your plan.', 'Open a pull request and let CodeSense review the change in the workflow.', 'Read findings with suggested fixes and security context.', 'Solo receives a weekly security digest; Team can route alerts through Slack and Discord webhooks.', 'Enterprise adds cloud, VPC, or air-gapped on-premises deployment after technical discovery.'][i]}</p></div></Card>)}</div>{platform && <div className="mt-16"><h2 className="font-display text-3xl">Integrations by plan</h2><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[600px] text-left text-sm"><thead><tr className="border-b border-line"><th className="p-3">Provider</th><th className="p-3">Solo</th><th className="p-3">Team</th><th className="p-3">Enterprise</th></tr></thead><tbody>{integrations.map(row => <tr key={row.name} className="border-b border-line"><th className="p-3">{row.name}</th><td className="p-3 text-ink-soft">{row.solo}</td><td className="p-3 text-ink-soft">{row.team}</td><td className="p-3 text-ink-soft">{row.enterprise}</td></tr>)}</tbody></table></div></div>}</Container></Section>
  </>
}
